# -*- coding: utf-8 -*-
"""InventarioForestalNacional_Dim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14lc4p34v0LLhnRkwjV8YJSdBG1AnVqxT
"""

import csv
import ipywidgets as widgets
from IPython.display import display
import os
from datetime import datetime

## To do
# Registrar brigadas y ponerlas en lista desplegable



numBrigadas = int(input("¿Cuántos grupos de datos desea agregar? | "))
print("Botón 'guardar' te permite guardar y editar los datos de dicho grupo de datos.")
numBrigadaActual = 0
brigadas = []
dataBrigadas = []

for _i in range(numBrigadas):
  brigadas.append("")

# función para guardar los datos de la brigada
def save_data(number,brigade,zoneAsigned,nameVeg,typeVeg,useVeg,idVeg,nameAnimal,typeAnimal,idAnimal):
  info=[
      number,
      brigade.value,
      zoneAsigned.value,
      nameVeg.value,
      typeVeg.value,
      useVeg.value,
      idVeg.value,
      nameAnimal.value,
      typeAnimal.value,
      idAnimal.value
  ]
  while len(brigadas) < number:
      brigadas.append("")
  brigadas[number-1] = info
  msg = f"¡Guardado Datos #{number}!✅"
  print(msg)

# función para elimninar datos de una brigada de la lista actual
def remove_data(number,brigadeList):
  if 0 < number <= len(brigadeList):
      brigadeList[number-1][0] = number
      brigadeList[number-1][1] = "(Eliminado)"
      for _i in range(2,len(brigadeList[number-1])):
        brigadeList[number-1][_i] = "N/A"
      msg = f"Datos #{number} eliminado correctamente🗑️"
  else:
      msg = f"No se pudo eliminar los datos #{number}. Número fuera de rango."
  print(msg)


# Función para crear nuevo grupo de datos
def createNewDataset(data_number):

  labelStyle = {'description_width':'130px'}

  print("-"*55)
  print(f"\nDatos {data_number}")
  numBrigade = widgets.IntText(
      description="Brigada número: ",
      style=labelStyle,
      )
  assignedZone = widgets.IntText(
      description="Conglomerado (#): ",
      style=labelStyle,
      )
  # Datos referentes a la especie vegetal de la zona
  commonNameVeg = widgets.Text(description="Nombre común: ",
      style=labelStyle,
      )
  typeVeg = widgets.Dropdown(description="Tipo de arbol: ",
      options=["Fustal","Latizal","Brinzal"],
      style=labelStyle
  )
  useVeg = widgets.Dropdown(description="Uso del arbol: ",
      options=["Medicinal","Alimenticio","Maderable"],
      style=labelStyle
  )
  idVeg = widgets.IntText(description="Cod. ID: ",
      style=labelStyle
  )

  # Datos referentes a la especie animal de la zona
  commonNameAnimal = widgets.Text(description="Nombre común: ",
      style=labelStyle,
  )
  typeAnimal = widgets.Dropdown(description="Tipo de animal: ",
      options=["Pez","Mamífero","Reptil","Ave","Anfibio"],
      style=labelStyle
  )
  idAnimal = widgets.IntText(description="Cod. ID: ",
      style=labelStyle
  )

  # Funciones de guardado y mostrar los elementos
  saveBoton = widgets.Button(description="guardar/editar", style={'button_color':'green'})
  saveBoton.on_click(lambda b,
                     number=data_number,
                     brigade=numBrigade,
                     zoneAsigned=assignedZone,
                     nameVeg=commonNameVeg,
                     typeVeg=typeVeg,
                     useVeg=useVeg,
                     idVeg=idVeg,
                     nameAnimal=commonNameAnimal,
                     typeAnimal=typeAnimal,
                     idAnimal=idAnimal
                     : save_data(number,brigade,zoneAsigned,nameVeg,typeVeg,useVeg,idVeg,nameAnimal,typeAnimal,idAnimal))

  removeBoton = widgets.Button(description="eliminar", style={'button_color':'red'})
  removeBoton.on_click(lambda b,
                       number = data_number,
                       brigadasList=brigadas
                       : remove_data(number,brigadasList))

  ui1 = widgets.HBox([numBrigade,assignedZone])
  uiVeg = widgets.VBox([commonNameVeg,typeVeg, useVeg,idVeg])
  uiAnimal = widgets.VBox([commonNameAnimal,typeAnimal,idAnimal])
  uiFuncs = widgets.HBox([saveBoton,removeBoton])

  display(ui1,"-----Especie vegetal-----",uiVeg,"-----Especie Animal-----",uiAnimal,uiFuncs)


# Función para guardar en forma de diccionario
def listToDict(brigadasList):
  global dataBrigadas
  dataBrigadas = []
  actualDate = datetime.now().strftime("%Y-%m-%d")

  for i in brigadasList:
    if i == "" or not isinstance(i, list):
      continue
    dataBrigadas.append({
        'Fecha Registro':actualDate,
        'Brigada #':i[1],
        'Conglomerado':i[2],
        'Nombre Común Vegetal':i[3],
        'Tipo Especie Vegetal':i[4],
        'Uso de Especie Vegetal':i[5],
        'ID Vegetal':i[6],
        'Nombre Común Animal':i[7],
        'Tipo Animal':i[8],
        'ID Animal':i[9]
    })
# función para guardar CSV
def saveCSV():
  listToDict(brigadas)
  global dataBrigadas
  nameCSV = 'IFN_Datos.csv'
  header = ['Fecha Registro','Brigada #','Conglomerado','Nombre Común Vegetal','Tipo Especie Vegetal','Uso de Especie Vegetal','ID Vegetal','Nombre Común Animal','Tipo Animal','ID Animal']

  fileExists= os.path.exists(nameCSV)

  with open(nameCSV, 'a', newline='', encoding='utf-8') as file:
        writer = csv.DictWriter(file, fieldnames=header)

        if not fileExists:
          writer.writeheader()

        writer.writerows(dataBrigadas)
        print(f"Información actual agregada con exito, guardado como {nameCSV}.")



# ----Start Here----
# Recolección de datos para los municipios iniciales
for _i in range(0,numBrigadas):
  numBrigadaActual += 1
  createNewDataset(numBrigadaActual)

# Botón para agregar un nuevo apartado de municipio
print("\n")
newData = widgets.Button(description="agregar grupo",style={'button_color':'orange'})

# función para agregar un nuevo municipio, después de haber iniciado
def addNewDataset(b):
    global numBrigadaActual
    numBrigadaActual += 1
    createNewDataset(numBrigadaActual)
print("-"*55)
newData.on_click(addNewDataset)
display(newData)

# Mostrar
saveCSVBoton = widgets.Button(description="guardar como CSV", style={'button_color':'purple'})
saveCSVBoton.on_click(lambda b: saveCSV())

ui3 = widgets.HBox([saveCSVBoton])
display(ui3)