# -*- coding: utf-8 -*-
"""inventarioForestalNacional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14lc4p34v0LLhnRkwjV8YJSdBG1AnVqxT
"""

import csv
import ipywidgets as widgets
from IPython.display import display, clear_output
import os
from datetime import datetime

# ────Estado global────────────────────────────────────
numBrigadaActual = 0

# Creación de zonas para mostrar los datos/formularios
salidaForms = widgets.Output()
startUpControls = widgets.Output()
actionButtonsOutput = widgets.Output()

numBrigadasInput = widgets.IntText(
    value=1,
    description='Número de brigadas:',
    disabled=False
)

# ──── Boton inicial ────────────────────────────────────
def showInputLogs(b):
  global numBrigadaActual,salidaForms,actionButtonsOutput
  numBrigadaActual = 0

  salidaForms = widgets.Output()
  actionButtonsOutput = widgets.Output()

  with startUpControls:
    clear_output(wait = True)
    display(widgets.HBox([numBrigadasInput,log]))

  display(salidaForms, actionButtonsOutput)

log = widgets.Button(description="Confirmar",style={'button_color':"purple"})


startLog = widgets.Button(description="Iniciar Registro",style={'button_color':'blue'})
startLog.on_click(showInputLogs)

display(startLog,startUpControls)

# ──── Lógica ────────────────────────────────────────────────
def logInfo(num):
    global numBrigadaActual, salidaForms, actionButtonsOutput

    numBrigadas = num.value
    numBrigadaActual = 0
    brigadasChoice = ["N/A",1,2,3]
    brigadas = []

    dataBrigadas = []

    with salidaForms:
     clear_output(wait = True)
    with actionButtonsOutput:
     clear_output(wait = True)

    for _i in range(numBrigadas):
      brigadas.append("")

    # ──── Guardar datos de un grupo ────────────────────────────
    def saveData(number,brigade,zoneAsigned,nameVeg,typeVeg,useVeg,idVeg,nameAnimal,typeAnimal,idAnimal):
      info=[
          number,
          brigade.value,
          zoneAsigned.value,
          nameVeg.value,
          typeVeg.value,
          useVeg.value,
          idVeg.value,
          nameAnimal.value,
          typeAnimal.value,
          idAnimal.value
      ]
      while len(brigadas) < number:
          brigadas.append("")
      brigadas[number-1] = info
      with salidaForms:
          print(f"¡Guardado Datos #{number}!✅")

    # ──── Eliminar datos de un grupo ────────────────────────────
    def remove_data(number,brigadeList):
      if 0 < number <= len(brigadeList) and isinstance(brigadeList[number-1],list):
          brigadeList[number-1][0] = number
          brigadeList[number-1][1] = "(Eliminado)"
          for i in range(2,len(brigadeList[number-1])):
            brigadeList[number-1][i] = "N/A"
          msg = f"Datos #{number} eliminado correctamente🗑️"
      else:
          msg = f"No se pudo eliminar los datos #{number}. Número fuera de rango."
      with salidaForms:
          print(msg)


    # ──── Crear formulario para grupo ────────────────────────────
    def createNewDataset(data_number):
      labelStyle = {'description_width':'130px'}

      numBrigade = widgets.Dropdown(
          options=brigadasChoice,
          description="Brigada número: ",
          style=labelStyle,
          )
      assignedZone = widgets.IntText(description="Conglomerado (#): ",style=labelStyle)
      # ──── Datos especie vegetal de la zona ───────────────────────────────
      commonNameVeg = widgets.Text(description="Nombre común: ",
                                   style=labelStyle)
      typeVeg = widgets.Dropdown(description="Tipo de arbol: ",
                                 options=["N/A","Fustal","Latizal","Brinzal"],
                                 style=labelStyle)
      useVeg = widgets.Dropdown(description="Uso del arbol: ",
                                options=["N/A","Medicinal","Alimenticio","Maderable"],
                                style=labelStyle)
      idVeg = widgets.IntText(description="Cod. ID: ",
                              style=labelStyle)

      # ──────────── Datos especie animal de la zona ────────────────────────
      commonNameAnimal = widgets.Text(description="Nombre común: ",
                                      style=labelStyle,)
      typeAnimal = widgets.Dropdown(description="Tipo de animal: ",
                                    options=["N/A","Pez","Mamífero","Reptil","Ave","Anfibio"],
                                    style=labelStyle)
      idAnimal = widgets.IntText(description="Cod. ID: ",
                                 style=labelStyle)

      # Funciones de guardado y mostrar los elementos
      saveBoton = widgets.Button(description="guardar/editar", style={'button_color':'green'})
      saveBoton.on_click(lambda b,
                        number=data_number,
                        brigade=numBrigade,
                        zoneAsigned=assignedZone,
                        nameVeg=commonNameVeg,
                        typeVeg=typeVeg,
                        useVeg=useVeg,
                        idVeg=idVeg,
                        nameAnimal=commonNameAnimal,
                        typeAnimal=typeAnimal,
                        idAnimal=idAnimal
                        : saveData(number,brigade,zoneAsigned,nameVeg,typeVeg,useVeg,idVeg,nameAnimal,typeAnimal,idAnimal))

      removeBoton = widgets.Button(description="eliminar", style={'button_color':'red'})
      removeBoton.on_click(lambda b,
                          number = data_number,
                          brigadasList=brigadas
                          : remove_data(number,brigadasList))

      ui1      = widgets.HBox([numBrigade,assignedZone])
      uiVeg    = widgets.VBox([commonNameVeg,typeVeg, useVeg,idVeg])
      uiAnimal = widgets.VBox([commonNameAnimal,typeAnimal,idAnimal])
      uiFuncs  = widgets.HBox([saveBoton,removeBoton])

      with salidaForms:
        print("-"*55)
        print(f"\nDatos {data_number}")
        display(ui1,
                "-----Especie vegetal-----",uiVeg,
                "-----Especie Animal-----",uiAnimal,
                uiFuncs)


    # ──── Convertir lista > Diccionario ────────────────────────────────
    def listToDict(brigadasList):
      result = []
      actualDate = datetime.now().strftime("%Y-%m-%d")

      for i in brigadasList:
        if i == "" or not isinstance(i, list):
          continue
        result.append({
            'Fecha Registro'        :actualDate,
            'Brigada #'             :i[1],
            'Conglomerado'          :i[2],
            'Nombre Común Vegetal'  :i[3],
            'Tipo Especie Vegetal'  :i[4],
            'Uso de Especie Vegetal':i[5],
            'ID Vegetal'            :i[6],
            'Nombre Común Animal'   :i[7],
            'Tipo Animal'           :i[8],
            'ID Animal'             :i[9]
        })
      return result

    # ──── Guardar CSV ────────────────────────────────────────────────────
    def saveCSV():
      dataBrigadas = listToDict(brigadas)
      nameCSV = 'IFN_Datos_General.csv'
      header = ['Fecha Registro','Brigada #','Conglomerado',
                'Nombre Común Vegetal','Tipo Especie Vegetal',
                'Uso de Especie Vegetal','ID Vegetal',
                'Nombre Común Animal','Tipo Animal','ID Animal']

      fileExists= os.path.exists(nameCSV)
      with open(nameCSV, 'a', newline='', encoding='utf-8') as file:
            writer = csv.DictWriter(file, fieldnames=header)

            if not fileExists:
              writer.writeheader()
            writer.writerows(dataBrigadas)
      with salidaForms:
          print(f"Información actual agregada con exito, guardado como {nameCSV}.")

    # ──── Filtrar CSV por brigada ────────────────────────────────────────
    def filterBrigade():
      nameCSV = 'IFN_Datos_General.csv'

      if not os.path.exists(nameCSV):
        with salidaForms:
          print("⚠️ No existe el archivo CSV, guarda los datos primero ⚠️")
        return

      with open(nameCSV, newline='', encoding='utf-8') as f:
        reader =csv.DictReader(f)
        all_rows = list(reader)
        brigadeValues = sorted(set(r['Brigada #'] for r in all_rows))

      if not brigadeValues:
        with salidaForms:
          print("⚠️ Archivo CSV está vacío ⚠️")
        return

      brigadeChoice = widgets.Dropdown(
          options=brigadeValues,
          descriptions="Filtrar brigada:",
          style={'description_width':'130px'}
      )
      applyFilter = widgets.Button(description="Filtrar", style={'button_color':'teal'})
      filterOutput = widgets.Output()

      def filterCSV(b):
        selected = brigadeChoice.value
        filtered = [r for r in all_rows if r['Brigada #'] == selected]
        outName = f'IFN_Brigada_{selected}.csv'
        header = list(filtered[0].keys()) if filtered else []

        with open(outName,'w',newline='',encoding='utf-8') as f:
          writer = csv.DictWriter(f, fieldnames = header)
          writer.writeheader()
          writer.writerows(filtered)

        with filterOutput:
          clear_output(wait=True)
          print(f"Filtrado: {len(filtered)} registro(s) de Brigada {selected}✅")
          print(f"Guardado como '{outName}'.")
      applyFilter.on_click(filterCSV)

      with salidaForms:
        print("\n ── Filtrar CSV por brigada ──")
        display(widgets.HBox([brigadeChoice,applyFilter]), filterOutput)


    # ──── Start Here ────────────────────────────────────────────────────
    # ──── Crear formularios iniciales ────────────────────────────────────
    for _i in range(0,numBrigadas):
      numBrigadaActual += 1
      createNewDataset(numBrigadaActual)

    # ──── Boton para crear grupo ────────────────────────────────────────────
    newData = widgets.Button(description="agregar grupo",style={'button_color':'orange'})

    # ──── Boton para crear nuevo set de datos ────────────────────────────────
    def addNewDataset(b):
        global numBrigadaActual
        numBrigadaActual += 1
        createNewDataset(numBrigadaActual)
    with salidaForms:
      print("-"*55)
    newData.on_click(addNewDataset)

    # ──── Botones de acción ────────────────────────────────────────────────
    saveCSVBoton = widgets.Button(description="guardar como CSV", style={'button_color':'purple'})
    filterCSVBoton = widgets.Button(description="Filtrar CSV", style={'button_color':'teal'})

    saveCSVBoton.on_click(lambda b: saveCSV())
    filterCSVBoton.on_click(lambda b: filterBrigade())

    ui3 = widgets.HBox([newData,saveCSVBoton,filterCSVBoton])
    with actionButtonsOutput:
      display(ui3)

log.on_click(lambda b: logInfo(numBrigadasInput))