# -*- coding: utf-8 -*-
"""inventarioForestalNacional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14lc4p34v0LLhnRkwjV8YJSdBG1AnVqxT
"""

import csv
import ipywidgets as widgets
from IPython.display import display, clear_output
import os
from datetime import datetime
import json

# ──── Persistencia de contadores IDs autocrecientes ───
idFile = 'IFN_counters.json'

def loadCounters():
  if os.path.exists(idFile):
    with open(idFile,'r') as f:
      return json.load(f)
  return {'lastVeg':1000,'lastAnimal':5000}

def saveCounters(counters):
  with open(idFile,'w') as f:
    json.dump(counters,f)

counters=loadCounters()
# ──────────────────────────────────────────────────────

# ──── Estado global────────────────────────────────────
numBrigadaActual = 0

# Creación de zonas para mostrar los datos/formularios
salidaForms = widgets.Output()
startUpControls = widgets.Output()
actionButtonsOutput = widgets.Output()

# ──── Boton inicial ────────────────────────────────────
def showInputLogs(b):
  global numBrigadaActual,salidaForms,actionButtonsOutput

  numBrigadaActual = 0

  salidaForms         = widgets.Output()
  actionButtonsOutput = widgets.Output()

  with startUpControls:
    clear_output(wait = True)
    display(startLog)

  display(salidaForms, actionButtonsOutput)

log = widgets.Button(description="Iniciar Registro",style={'button_color':'blue'})
log.on_click(showInputLogs)

startLog = widgets.Button(description="Confirmar",style={'button_color':'purple'})
startLog.on_click(logInfo)
display(log,startUpControls)

# ──── Lógica ────────────────────────────────────────────────
def logInfo(b):
    global numBrigadaActual, salidaForms, actionButtonsOutput

    counters = loadCounters()
    numBrigadaActual = 0
    brigadasChoice = ["N/A",1,2,3]
    brigadas = []

    dataBrigadas = []

    with salidaForms:
     clear_output(wait = True)
    with actionButtonsOutput:
     clear_output(wait = True)

    labelStyle = {'description_width':'130px'}

    # ──── Formulario único ─────────────────────────────────
    numBrigade = widgets.Dropdown(options=brigadasChoice,description="Brigada #:",style=labelStyle)

    assignedZone = widgets.BoundedIntText(min=1,max=999,description="Conglomerado (#): ",style=labelStyle)

    # ──── Datos especie vegetal de la zona ───────────────────────────────
    commonNameVeg = widgets.Text(description="Nombre común: ", style=labelStyle)
    typeVeg = widgets.Dropdown(description="Tipo de arbol: ",
                                options=["N/A","Fustal","Latizal","Brinzal"], style=labelStyle)
    useVeg = widgets.Dropdown(description="Uso del arbol: ",
                              options=["N/A","Medicinal","Alimenticio","Maderable"], style=labelStyle)
    idVeg = widgets.Label(value=f"Cód. Vegetal asignado: {counters['lastVeg']+1}")

    # ──────────── Datos especie animal de la zona ────────────────────────
    commonNameAnimal = widgets.Text(description="Nombre común: ", style=labelStyle,)
    typeAnimal = widgets.Dropdown(description="Tipo de animal: ",
                                  options=["N/A","Pez","Mamífero","Reptil","Ave","Anfibio"], style=labelStyle)
    idAnimal = widgets.Label(value=f"Cód. Animal asignado: {counters['lastAnimal']+1}")

    validationOutput = widgets.Output()

    # ──── Validación de campos ────────────────────────────────────────────
    def validateForm():
      errors=[]
      if numBrigade.value == "N/A":
        errors.append("- Selecciona una brigada válida (No 'N/A').")
      if not commonNameVeg.value.strip():
        errors.append("- El nombre común de la especie vegetal está vacío.")
      if typeVeg.value == "N/A":
        errors.append("- Selecciona un Tipo de árbol válido (No 'N/A').")
      if useVeg.value == "N/A":
        errors.append("- Selecciona un Uso del árbol válido (No 'N/A').")
      if not commonNameAnimal.value.strip():
        errors.append("- El nombre común de la especie animal está vacío.")
      if typeAnimal.value == "N/A":
        errors.append("- Selecciona un Tipo de animal válido (No 'N/A').")
      return errors
    # ────────────────────────────────────────────────────────────────────────
    # ──── Guardar registro validado ────────────────────────────────────────
    def saveData(b):
      global counters
      errors = validateForm()

      with validationOutput:
        clear_output(wait=True)
        if errors:
          msg = "<b style='color:red'>⚠️ Corrige los siguientes campos antes de guardar:</b><br>"+"<br>".join(errors)
          display(widgets.HTML(msg))
          return

      counters['lastVeg'] +=1
      counters['lastAnimal'] +=1
      saveCounters(counters)

      info=[
          len(brigadas)+1,
          numBrigade.value,
          assignedZone.value,
          commonNameVeg.value,
          typeVeg.value,
          useVeg.value,
          counters['lastVeg'],
          commonNameAnimal.value,
          typeAnimal.value,
          counters['lastAnimal']
      ]
      brigadas.append(info)

      # Actualizar label para el siguiente registro
      idVeg.value = f"Cód. Vegetal asignado: {counters['lastVeg']+1}"
      idAnimal.value = f"Cód. Animal asignado: {counters['lastAnimal']+1}"
      # Limpiar formulario para el siguiente registro
      numBrigade.value        = "N/A"
      assignedZone.value      = 1
      commonNameVeg.value     = ""
      typeVeg.value           = "N/A"
      useVeg.value            = "N/A"
      commonNameAnimal.value  = ""
      typeAnimal.value        = "N/A"

      with validationOutput:
        clear_output(wait=True)
        display(widgets.HTML( f"<b style='color:lightgreen'>✅ Registro #{len(brigadas)} guardado — "
                f"Cód. Vegetal: {counters['lastVeg']} | Cód. Animal: {counters['lastAnimal']}</b>"
            ))

    # ──── Fix Colab ────────────────────────────────────────────────────────────
    def refreshOutput(b):
      with salidaForms:
        print("Refrescado correctamente")

    refreshBoton = widgets.Button(description="🔄Refrescar vista",style={'button_color':'gray'})
    refreshBoton.on_click(refreshOutput)

    saveBoton = widgets.Button(description="Revisar y guardar", style={'button_color':'green'})
    saveBoton.on_click(saveData)

    # ──── Generar formulario ───────────────────────────────────────────────────
    ui1      = widgets.HBox([numBrigade,assignedZone])
    uiVeg    = widgets.VBox([commonNameVeg,typeVeg, useVeg,idVeg])
    uiAnimal = widgets.VBox([commonNameAnimal,typeAnimal,idAnimal])
    with salidaForms:
      display(refreshBoton,
              widgets.HTML("<b>───────────────────────────────────────────────────</b>"),
              ui1,
              widgets.HTML("<b>-----Especie vegetal (Árbol)-----</b>"),uiVeg,
              widgets.HTML("<b>-----Especie Animal-----</b>"),uiAnimal,
              saveBoton,
              validationOutput,
              widgets.HTML("<b>───────────────────────────────────────────────────</b>")
              )

    # ──── Convertir lista > Diccionario ────────────────────────────────
    def listToDict(brigadasList):
      result = []
      actualDate = datetime.now().strftime("%Y-%m-%d")

      for i in brigadasList:
        if i == "" or not isinstance(i, list):
          continue
        result.append({
            'Fecha Registro'        :actualDate,
            'Brigada #'             :i[1],
            'Conglomerado'          :i[2],
            'Nombre Común Vegetal'  :i[3],
            'Tipo Especie Vegetal'  :i[4],
            'Uso de Especie Vegetal':i[5],
            '# Vegetal'             :i[6],
            'Nombre Común Animal'   :i[7],
            'Tipo Animal'           :i[8],
            '# Animal'              :i[9]
        })
      return result

    # ──── Guardar CSV ────────────────────────────────────────────────────
    def saveCSV():
      from google.colab import files

      dataBrigadas = listToDict(brigadas)
      nameCSV = 'IFN_Datos_General.csv'
      header = ['Fecha Registro','Brigada #','Conglomerado',
                'Nombre Común Vegetal','Tipo Especie Vegetal',
                'Uso de Especie Vegetal','# Vegetal',
                'Nombre Común Animal','Tipo Animal','# Animal']

      fileExists= os.path.exists(nameCSV)
      with open(nameCSV, 'a', newline='', encoding='utf-8') as file:
            writer = csv.DictWriter(file, fieldnames=header)

            if not fileExists:
              writer.writeheader()
            writer.writerows(dataBrigadas)
      files.download(nameCSV)
      with salidaForms:
          print(f"Información actual agregada con exito, guardado como '{nameCSV}'.")

    # ──── Filtrar CSV por brigada ────────────────────────────────────────
    def filterBrigade():
      nameCSV = 'IFN_Datos_General.csv'

      if not os.path.exists(nameCSV):
        with salidaForms:
          print("⚠️ No existe el archivo CSV, guarda los datos primero ⚠️")
        return

      with open(nameCSV, newline='', encoding='utf-8') as f:
        reader =csv.DictReader(f)
        all_rows = list(reader)
        brigadeValues = sorted(set(r['Brigada #'] for r in all_rows))

      if not brigadeValues:
        with salidaForms:
          print("⚠️ Archivo CSV está vacío ⚠️")
        return

      brigadeChoice = widgets.Dropdown(
          options=brigadeValues,
          descriptions="Filtrar brigada:",
          style={'description_width':'130px'}
      )
      applyFilter = widgets.Button(description="Filtrar", style={'button_color':'teal'})
      filterOutput = widgets.Output()

      def filterCSV(b):
        from google.colab import files
        selected = brigadeChoice.value
        filtered = [r for r in all_rows if r['Brigada #'] == selected]
        outName = f'IFN_Brigada_{selected}.csv'
        header = list(filtered[0].keys()) if filtered else []

        with open(outName,'w',newline='',encoding='utf-8') as f:
          writer = csv.DictWriter(f, fieldnames = header)
          writer.writeheader()
          writer.writerows(filtered)
        files.download(outName)
        with filterOutput:
          clear_output(wait=True)
          print(f"Filtrado: {len(filtered)} registro(s) de Brigada {selected}✅")
          print(f"Guardado como '{outName}'.")
      applyFilter.on_click(filterCSV)

      with salidaForms:
        print("\n ── Filtrar CSV por brigada ──")
        display(widgets.HBox([brigadeChoice,applyFilter]), filterOutput)


    # ──── Start Here ────────────────────────────────────────────────────

    # ──── Botones de acción ────────────────────────────────────────────────
    saveCSVBoton = widgets.Button(description="guardar como CSV", style={'button_color':'purple'})
    filterCSVBoton = widgets.Button(description="Filtrar CSV", style={'button_color':'teal'})

    saveCSVBoton.on_click(lambda b: saveCSV())
    filterCSVBoton.on_click(lambda b: filterBrigade())

    ui3 = widgets.HBox([saveCSVBoton,filterCSVBoton])
    with actionButtonsOutput:
      display(ui3)



